import { Card } from '../components/Card.js'
import { Badge } from '../components/Badge.js'
import { EmptyState } from '../components/EmptyState.js'
import { getAll, getDashboardMetrics, getRecord } from '../services/dataService.js'
import { formatCurrency, formatDate, formatRelativeTime } from '../utils/helpers.js'
import { icon } from '../utils/icons.js'

export function render(container) {
  const metrics = getDashboardMetrics()
  const events = getAll('calendarEvents').filter((event) => { const diff = (new Date(event.date) - new Date()) / 86400000; return diff >= 0 && diff <= 7 }).sort((a, b) => new Date(a.date) - new Date(b.date))
  const tasksToday = getAll('tasks').filter((task) => task.date === new Date().toISOString().slice(0, 10))
  const payments = getAll('payments').sort((a, b) => new Date(b.dueDate) - new Date(a.dueDate)).slice(0, 4)
  const recentActivity = [...payments.map((payment) => ({ title: `${getRecord('horses', payment.horseId)?.name || 'Boarding'} invoice ${payment.invoiceNumber}`, detail: `${formatCurrency(payment.amount)} · ${payment.status}`, when: payment.paidDate || payment.dueDate })), ...getAll('tasks').filter((task) => task.completed).slice(0, 3).map((task) => ({ title: task.title, detail: `Completed by ${task.assignedTo}`, when: task.date }))].sort((a, b) => new Date(b.when) - new Date(a.when)).slice(0, 6)

  container.innerHTML = `
    <div class="page-shell">
      <section class="page-header"><div><p class="text-sm uppercase tracking-[0.25em] text-slate-400">Welcome back</p><h1 class="mt-2 text-3xl font-semibold text-slate-900">Stable overview for ${formatDate(new Date().toISOString())}</h1><p class="mt-2 max-w-2xl text-sm text-slate-500">A calm, complete overview of horses, boarders, revenue and care tasks across the yard.</p></div></section>
      <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">${Card({ label: 'Total horses', value: metrics.totalHorses, icon: '🐴', helper: 'Active residents and training horses' })}${Card({ label: 'Occupied stalls', value: metrics.occupiedStalls, icon: icon('grid', 'h-5 w-5'), helper: `${metrics.availableStalls} stalls available` })}${Card({ label: 'Available stalls', value: metrics.availableStalls, icon: icon('home', 'h-5 w-5'), helper: 'Ready for new arrivals' })}${Card({ label: 'Monthly revenue', value: formatCurrency(metrics.monthlyRevenue), icon: icon('dollar', 'h-5 w-5'), helper: 'Paid boarding invoices this month' })}</section>
      <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">${Card({ label: 'Due payments', value: metrics.duePayments, icon: icon('alert', 'h-5 w-5'), helper: 'Invoices awaiting payment' })}${Card({ label: 'Tasks today', value: metrics.tasksToday, icon: icon('checkSquare', 'h-5 w-5'), helper: 'Daily care and admin tasks' })}${Card({ label: 'Upcoming farrier', value: metrics.upcomingFarrierVisits, icon: icon('horse', 'h-5 w-5'), helper: 'Visits on the calendar' })}${Card({ label: 'Upcoming vet', value: metrics.upcomingVetVisits, icon: icon('calendar', 'h-5 w-5'), helper: 'Health appointments scheduled' })}</section>
      <section class="grid gap-6 xl:grid-cols-[1.7fr,1fr]">
        <div class="space-y-6">
          <div class="panel p-5"><div class="mb-4 flex items-center justify-between"><h2 class="section-title">Upcoming events</h2><span class="text-sm text-slate-400">Next 7 days</span></div><div class="space-y-3">${events.length ? events.map((event) => `<div class="flex items-start justify-between gap-3 rounded-2xl bg-slate-50 px-4 py-3"><div><div class="flex items-center gap-2"><span class="h-3 w-3 rounded-full" style="background:${event.color}"></span><p class="font-medium text-slate-800">${event.title}</p>${Badge(event.type, event.type.replace('_', ' '))}</div><p class="mt-1 text-sm text-slate-500">${getRecord('horses', event.horseId) ? `${getRecord('horses', event.horseId).name} · ` : ''}${event.notes}</p></div><p class="whitespace-nowrap text-sm text-slate-500">${formatDate(event.date, { day: 'numeric', month: 'short' })} · ${event.time}</p></div>`).join('') : EmptyState({ icon: '📅', title: 'No upcoming events', message: 'Your next week is clear right now.' })}</div></div>
          <div class="grid gap-6 lg:grid-cols-2">
            <div class="panel p-5"><div class="mb-4 flex items-center justify-between"><h2 class="section-title">Today’s tasks</h2><span class="text-sm text-slate-400">${tasksToday.length} scheduled</span></div><div class="space-y-3">${tasksToday.length ? tasksToday.map((task) => `<div class="rounded-2xl border border-slate-100 px-4 py-3"><div class="flex items-center justify-between gap-3"><p class="font-medium text-slate-800">${task.title}</p>${Badge(task.priority)}</div><p class="mt-1 text-sm text-slate-500">${task.assignedTo} · ${task.type} · ${task.dueTime}</p></div>`).join('') : '<p class="text-sm text-slate-500">No tasks assigned for today.</p>'}</div></div>
            <div class="panel p-5"><div class="mb-4 flex items-center justify-between"><h2 class="section-title">Recent activity</h2><span class="text-sm text-slate-400">Live from storage</span></div><div class="space-y-3">${recentActivity.map((item) => `<div class="flex items-start gap-3 rounded-2xl bg-slate-50 px-4 py-3"><div class="mt-1 h-2.5 w-2.5 rounded-full bg-forest"></div><div><p class="font-medium text-slate-800">${item.title}</p><p class="text-sm text-slate-500">${item.detail}</p><p class="mt-1 text-xs text-slate-400">${formatRelativeTime(item.when)}</p></div></div>`).join('')}</div></div>
          </div>
        </div>
        <aside class="panel p-5"><div class="mb-4 flex items-center justify-between"><h2 class="section-title">Notifications</h2><span class="text-sm text-slate-400">Attention needed</span></div><div class="space-y-3">${metrics.notifications.length ? metrics.notifications.map((item) => `<div class="rounded-2xl border border-slate-100 p-4"><div class="flex items-center justify-between gap-3"><p class="font-medium text-slate-800">${item.title}</p>${Badge(item.type)}</div><p class="mt-2 text-sm text-slate-500">${item.message}</p><p class="mt-2 text-xs text-slate-400">${formatDate(item.date)}</p></div>`).join('') : '<p class="text-sm text-slate-500">Everything looks calm right now.</p>'}</div></aside>
      </section>
    </div>`
}
