import { confirmDialog } from '../components/ConfirmDialog.js'
import { notify } from '../components/Notification.js'
import { exportData, getSettings, importData, resetData, upsertSettings } from '../services/dataService.js'

export function render(container) {
  const settings = getSettings()
  container.innerHTML = `<div class="page-shell"><div><h1 class="text-3xl font-semibold text-slate-900">Settings</h1><p class="mt-2 text-sm text-slate-500">Configure stable details, display preferences and local data management tools.</p></div><div class="grid gap-6 xl:grid-cols-[1.4fr,1fr]"><form id="settings-form" class="panel p-6"><h2 class="section-title">Stable information</h2><div class="mt-5 grid gap-5 md:grid-cols-2">${[['stableName','Stable name','text'],['managerName','Manager name','text'],['phone','Phone','tel'],['email','Email','email'],['address','Address','text']].map(([name,label,type]) => `<label class="${name === 'address' ? 'md:col-span-2' : ''}"><span class="field-label">${label}</span><input class="field" name="${name}" type="${type}" value="${settings[name] || ''}" required /></label>`).join('')}<label><span class="field-label">Currency</span><select class="field" name="currency">${['EUR','SEK','GBP'].map((value) => `<option value="${value}" ${settings.currency === value ? 'selected' : ''}>${value}</option>`).join('')}</select></label><label><span class="field-label">Default calendar view</span><select class="field" name="defaultCalendarView">${['month','week','day'].map((value) => `<option value="${value}" ${settings.defaultCalendarView === value ? 'selected' : ''}>${value}</option>`).join('')}</select></label><label class="md:col-span-2 flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3"><input type="checkbox" name="compactMode" ${settings.compactMode ? 'checked' : ''} /><span class="text-sm text-slate-600">Enable compact display spacing</span></label></div><div class="mt-6 flex justify-end"><button class="btn-primary" type="submit">Save settings</button></div></form><div class="space-y-6"><div class="panel p-6"><h2 class="section-title">Data management</h2><div class="mt-5 space-y-3"><button class="btn-ghost w-full justify-between" type="button" data-export>Export data <span>JSON</span></button><label class="btn-ghost flex w-full cursor-pointer justify-between" for="import-data">Import data <span>Upload</span></label><input id="import-data" class="hidden" type="file" accept="application/json" /><button class="btn-secondary w-full justify-between" type="button" data-clear>Clear and reseed <span>Reset</span></button></div></div><div class="panel p-6"><h2 class="section-title">Notes</h2><p class="mt-4 text-sm text-slate-500">All data is stored locally in the browser via LocalStorage. Export regularly if you need a backup.</p></div></div></div></div>`
  container.querySelector('#settings-form').addEventListener('submit', (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.target).entries()); payload.compactMode = event.target.compactMode.checked; upsertSettings(payload); notify('Settings saved.', 'success') })
  container.querySelector('[data-export]').addEventListener('click', () => { const blob = new Blob([JSON.stringify(exportData(), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'stable-manager-export.json'; link.click(); URL.revokeObjectURL(url); notify('Data export created.', 'success') })
  container.querySelector('#import-data').addEventListener('change', async (event) => { const file = event.target.files?.[0]; if (!file) return; importData(JSON.parse(await file.text())); notify('Data imported successfully.', 'success'); render(container) })
  container.querySelector('[data-clear]').addEventListener('click', async () => { if (!(await confirmDialog({ title: 'Reset local data', message: 'This will clear local storage for the app and restore seed data.', confirmText: 'Reset data' }))) return; resetData(); notify('Data reset to sample records.', 'success'); render(container) })
}
